# json name을 snake case로 변환해서 정보를 주고 받음
server:
  jackson:
    property-naming-strategy: SNAKE_CASE

# jdbc:mysql://{host}:{port}/{db_name}
spring:
  mvc:
    servlet:
      path: /sushi
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-request-size: 512MB
      max-file-size: 512MB

auth:
  jwt:
    secret: ${JWT_SECRET_KEY}
    header: Authorization
    prefix: Bearer
    exp:
      access: 609600

file:
  path: ${FILE_PATH}